In [8]:
import pandas as pd
df = pd.read_csv("myntra.csv")
df = df.head(5000)
df

,name,sku,mpn,price,in_stock,currency,brand,description,images,gender
0,DKNY Unisex Black & Grey Printed Medium Trolle...,10017413,10017413,11745,True,INR,DKNY,"Black and grey printed medium trolley bag, sec...",http://assets.myntassets.com/assets/images/100...,Unisex
1,EthnoVogue Women Beige & Grey Made to Measure ...,10016283,10016283,5810,True,INR,EthnoVogue,Beige & Grey made to measure kurta with churid...,http://assets.myntassets.com/assets/images/100...,Women
2,SPYKAR Women Pink Alexa Super Skinny Fit High-...,10009781,10009781,899,True,INR,SPYKAR,Pink coloured wash 5-pocket high-rise cropped ...,http://assets.myntassets.com/assets/images/100...,Women
3,Raymond Men Blue Self-Design Single-Breasted B...,10015921,10015921,5599,True,INR,Raymond,Blue self-design bandhgala suitBlue self-desig...,http://assets.myntassets.com/assets/images/pro...,Men
4,Parx Men Brown & Off-White Slim Fit Printed Ca...,10017833,10017833,759,True,INR,Parx,"Brown and off-white printed casual shirt, has ...",http://assets.myntassets.com/assets/images/pro...,Men
...,...,...,...,...,...,...,...,...,...,...
4995,Indian Terrain Men Grey Melange Printed Round ...,10146983,10146983,449,True,INR,Indian Terrain,"Grey Melange printed T-shirt, has a round neck...",http://assets.myntassets.com/assets/images/101...,Men
4996,Indian Terrain Men Blue Brooklyn Slim Fit Low-...,10146821,10146821,1124,True,INR,Indian Terrain,"Blue dark wash 5-pocket low-rise jeans, clean ...",http://assets.myntassets.com/assets/images/101...,Men
4997,Indian Terrain Men Red Solid Henley Neck T-shirt,10147717,10147717,719,True,INR,Indian Terrain,"Red solid T-shirt, has a Henley neck, and long...",http://assets.myntassets.com/assets/images/101...,Men
4998,Indian Terrain Men Navy Blue Brooklyn Slim Fit...,10148849,10148849,1839,True,INR,Indian Terrain,"Navy Blue solid mid-rise trousers, button clos...",http://assets.myntassets.com/assets/images/101...,Men
4999,Indian Terrain Men Navy Blue Brooklyn Slim Fit...,10148929,10148929,1919,True,INR,Indian Terrain,"Navy blue solid low-rise trousers, button clos...",http://assets.myntassets.com/assets/images/101...,Men

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
df['name'].dtypes

dtype('O')

In [3]:

# def process_text(text):
#     text = ' '.join(text.split())
#     text = text.lower()
#     return text
# df['description'] = df['description'].apply(process_text)

In [42]:
# df = df[df['description'].notna()]
# df.reset_index(inplace=True)
# def process_text(text):
#     text = ' '.join(text.split())
#     text = text.lower()
#     return text
# df['description'] = df.apply(lambda x: process_text(x.description),axis=1)

In [10]:
tf_idf = TfidfVectorizer(stop_words='english')
tf_idf_matrix = tf_idf.fit_transform(df['description']);

In [11]:
cosine_similarity_matrix = cosine_similarity(tf_idf_matrix, tf_idf_matrix)

In [13]:
def index_from_title(df,title):
  return df[df['name']==title].index.values[0]

# def title_from_index(df,index):
#   return df[df.index==index].original_title.values[0]

def recommendations( original_title, df,cosine_similarity_matrix,number_of_recommendations):
  index = index_from_title(df,original_title)
  similarity_scores = list(enumerate(cosine_similarity_matrix[index]))
  similarity_scores_sorted = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
  recommendations_indices = [t[0] for t in similarity_scores_sorted[1:(number_of_recommendations+1)]]
  return df['name'].iloc[recommendations_indices]

In [14]:
recommendations("Parx Men Brown Tapered Fit Solid Regular Trousers", df, cosine_similarity_matrix, 10)

396        Parx Men Khaki Slim Fit Solid Regular Trousers
465     Parx Men Brown Original Slim Fit Solid Regular...
514     Parx Men Brown Tapered Fit Solid Regular Trousers
698     Parx Men Blue Original Tapered Fit Solid Regul...
968      Parx Men Grey Regular Fit Solid Regular Trousers
735     Parx Men Navy Blue Slim Fit Solid Regular Trou...
1507    Park Avenue Men Navy Blue Regular Fit Solid Re...
863      Parx Men Blue Tapered Fit Solid Regular Trousers
1235    Park Avenue Men Brown Regular Fit Solid Formal...
1747    Park Avenue Men Brown Regular Fit Solid Formal...
Name: name, dtype: object